spring.application.name=urlshortener

#MySQL connection
spring.datasource.url=${SQLDB_HOST}
spring.datasource.username=${SQLDB_USERNAME}
spring.datasource.password=${SQLDB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT}

#logging.level.org.springframework.data.redis=DEBUG
#logging.level.org.springframework.data.redis.connection=DEBUG
#logging.level.org.springframework.data.redis.core=DEBUG
#logging.level.io.lettuce.core=DEBUG